name: Docker

on:
  push:
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.tatasurarta }}
          password: ${{ secrets.Keluarga2021 }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: breakdowns/mega-sdk-python:latest

      - name: Alert via Telegram
        run: |
          function sendTG() {
              curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" \
              --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown&disable_notification=True"
          }
          sendTG "*Docker container has been updated:* [Link](https://hub.docker.com/r/breakdowns/mega-sdk-python/tags)" &> /dev/null
